# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-29 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramvalue',
            old_name='param_setting',
            new_name='param',
        ),
    ]
